analytics: {}
color:
  brandColors:
    - '#2e3f47'
    - '#626b74'
    - '#e9ddeb'
    - '#bbb5c1'
    - '#0d1e25'
  brandStrength: 0.753378
  lightness: 0.528716
  rhythmicContrast: 0.278716
  saturation: 0.317567
cta: {}
layout_spectrum: 0.30556
name: Water to GO
opengraph: {}
purpose:
  - name: engagement
typography_spectrum: 1
