analytics: {}
color:
  brandColors:
    - '#E0E0C8'
    - '#301010'
    - '#606890'
    - '#B03810'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.875
  rhythmicContrast: 0.75
  saturation: 0.5625
cta: {}
layout_spectrum: 0.773648
name: Water to GO
opengraph: {}
purpose:
  - name: engagement
typography_spectrum: 0.236486
