name: Water to GO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56444
title: Water to GO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e3f47'
    - '#626b74'
    - '#e9ddeb'
    - '#bbb5c1'
    - '#0d1e25'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose:
  - name: engagement
    item: null
    url: null
